### ISSUE TITLE
not support in Android <= 6.0

### ISSUE THREAD

**Issue by nowilike** [aws/aws-iot-device-sdk-java#104]
I am working on an Android 5.1 device, I got a runtime exception

06-14 10:36:40.879 W/System.err: java.lang.NoSuchMethodError: No virtual method setEndpointIdentificationAlgorithm(Ljava/lang/String;)V in class Ljavax/net/ssl/SSLParameters; or its super classes (declaration of 'javax.net.ssl.SSLParameters' appears in /system/framework/core-libart.jar)
06-14 10:36:40.879 W/System.err:     at com.amazonaws.services.iot.client.util.AwsIotTlsSocketFactory.ensureTls(AwsIotTlsSocketFactory.java:124)
06-14 10:36:40.879 W/System.err:     at com.amazonaws.services.iot.client.util.AwsIotTlsSocketFactory.createSocket(AwsIotTlsSocketFactory.java:80)

I found that Android >= 7.0 has the correct version of SSLParameters (1.7), before 7.0 it is 1.6 and doesn't have the method setEndpointIdentificationAlgorithm.

Is that possible to make this sdk support jdk 1.6?

thx.

**Comment by ColdenCullen** [comment]
Hi, unfortunately the SDK does require Java 1.7 or higher. Also, the v1 IoT SDKs are in maintenance mode and it is unlikely any significant changes or new functionality will be added to them.
